[package]
name = "goose_dsp"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.14"
eframe = "0.21"
rustfft = "6.0"
dasp = { version = "0.11", features = ["signal"] }
hound = "3.4"
rfd = "0.8"